### ISSUE TITLE
Admonition boxes in tutorial illegible on docs.rs dark themes

### ISSUE THREAD

**Issue by trajing** [bread-graphics/breadx#4]
While admonition boxes such as the following from the [basics tutorial](https://docs.rs/breadx/0.1.0/breadx/tutorials/basics/index.html) are perfectly legible on light mode:

![image](https://user-images.githubusercontent.com/6445075/100698253-99c91780-335d-11eb-8d8e-bf932b1494a9.png)

docs.rs also provides a dark mode (which, by my understanding, is the default when the reader's system is configured to prefer a dark mode), under which the content of these admonition boxes becomes practically illegible:

![image](https://user-images.githubusercontent.com/6445075/100698449-152ac900-335e-11eb-8110-e14486841e4e.png)

It is potentially worth noting that docs.rs provides an additional dark mode, ayu, under which heading text is even lighter.

To reproduce: visit any of the tutorial pages containing admonition boxes, click on the paintbrush icon next to the docs.rs search bar, and select "dark" or "ayu".

**Comment by not-a-seagull** [comment]
Thanks for filing this issue!

This issue could probably be fixed by adding `color: #222` to the div boxes, to ensure all text within is hard-set to be black. The main issue is that it might contrast with the dark background too much. I'll try to come up with something within the next few days.

**Comment by not-a-seagull** [comment]
Noting that I've temporarily ameliorated this issue by removing the backgrounds for these divs. However, I'm leaving this issue open for the time being because I'd like to find a way to restore these backgrounds while only modifying the text within.

**Comment by notgull** [comment]
Admonition boxes are gone, so this issue is no longer in effect
