### ISSUE TITLE
Interfacing with XLib

### ISSUE THREAD

**Issue by codic12** [bread-graphics/breadx#66]
Is it possible to interface xlib with breadx?

**Comment by notgull** [comment]
I'm currently working on a layer that implements `Display` and `AsyncDisplay` over XCB and Xlib connections.

**Comment by notgull** [comment]
Solved with the creation of [whitebreadx](https://github.com/bread-graphics/whitebreadx).

**Comment by codic12** [comment]
Fantastic, thank you!
