### ISSUE TITLE
Update nix version

### ISSUE THREAD

**Issue by figsoda** [bread-graphics/breadx#67]
[RUSTSEC-2021-0119](https://rustsec.org/advisories/RUSTSEC-2021-0119) is causing dependent crates to fail [cargo-audit](https://github.com/RustSec/rustsec/tree/main/cargo-audit)

**Comment by notgull** [comment]
Thanks for bringing this to my attention! Could you file a PR that changes this, please?

**Comment by notgull** [comment]
#74 resolves this issue
