### ISSUE TITLE
Unable to connect to the X11 server: FailedToConnect

### ISSUE THREAD

**Issue by pudnax** [bread-graphics/breadx#8]
Fails trying to run tutorial

Backtrace:
```Bash
      at /src/main.rs:97
        96 │
        97 >     let mut conn = breadx::DisplayConnection::create(None, None)?;
        98 │     let root = conn.default_screen().root;
        99 │     let window = conn.create_window(
   7: core::ops::function::FnOnce::call_once::h4cf5fef69ffc6cc4
      at /home/pudi3/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
       225 │     /// Performs the call operation.
       226 │     #[unstable(feature = "fn_traits", issue = "29625")]
       227 >     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
       228 │ }
       229 │
```

I can avoid this error running `xhost local:root`, but i concern by security reasons.

**Comment by pudnax** [comment]
```Bash
$ echo $DISPLAY
:0
$ inxi -G
Graphics:  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
           Device-2: NVIDIA GM108M [GeForce MX130] driver: nvidia v: 455.45.01
           Device-3: IMC Networks USB2.0 VGA UVC WebCam type: USB driver: uvcvideo
           Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia resolution: 1920x1080~60Hz
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.2.3
```

**Comment by not-a-seagull** [comment]
Thanks for filing this issue!

Connecting to the X server has a lot of corner cases. By any chance could you run `lsof | grep .X11-unix` and giving the results here? It'll tell me what socket you're connected to.

**Comment by pudnax** [comment]
If fails to show anything so i found by myself.
Running the `basic` example from repo:
```Bash
basic     4172219                   pudi3  cwd       DIR                8,4      4096   17818774 /home/komm/Flush/breadx
basic     4172219                   pudi3  rtd       DIR                8,5      4096          2 /
basic     4172219                   pudi3  txt       REG                8,4  18402080   12520817 /home/pudi3/.cache/cargo-target/debug/examples/basic
basic     4172219                   pudi3  mem       REG                8,5     18608    1451220 /usr/lib/libdl-2.32.so
basic     4172219                   pudi3  mem       REG                8,5    594704    1446404 /usr/lib/libgcc_s.so.1
basic     4172219                   pudi3  mem       REG                8,5    158744    1451254 /usr/lib/libpthread-2.32.so
basic     4172219                   pudi3  mem       REG                8,5   2159552    1451213 /usr/lib/libc-2.32.so
basic     4172219                   pudi3  mem       REG                8,5    207944    1451202 /usr/lib/ld-2.32.so
basic     4172219                   pudi3    0u      CHR              136,1       0t0          4 /dev/pts/1
basic     4172219                   pudi3    1u      CHR              136,1       0t0          4 /dev/pts/1
basic     4172219                   pudi3    2u      CHR              136,1       0t0          4 /dev/pts/1
basic     4172219                   pudi3    3u     unix 0x00000000cd0ce7fd       0t0    4812930 type=STREAM (CONNECTED)
```
Sorry if i'm doing something wrong >.>
I'm on manjaro + i3

**Comment by psychon** [comment]
> I can avoid this error running xhost local:root, but i concern by security reasons.

What output does `xhost` produce before you add root? For me, this command says:
```
$ xhost 
access control enabled, only authorized clients can connect
SI:localuser:my_account_name_here
```
This means that any process running as my user can connect to the X11 server without having to authenticate. Other clients can only connect if they authenticate with one of the secrets that `xauth list` produces. AFAIK, breadx currently does not support parsing `~/.Xauthority` (and I also guess that the error message for this case could be improved; right now it only produces an error in the following code, but if it were to parse the `SetupFailed` or `SetupAuthenticate` reply, it could print/return the reason field: https://github.com/not-a-seagull/breadx/blob/b0f76722285715ccbe4d6447e373208c5aa68785/src/display/mod.rs#L304-L307)

**Comment by pudnax** [comment]
```
$ xhost
access control enabled, only authorized clients can connect
LOCAL:
```

**Comment by psychon** [comment]
Hm, weird, I cannot reproduce this (the below is #7 so that the example connects to the right X11 server):
```
$ DISPLAY=:1 xhost
access control enabled, only authorized clients can connect
LOCAL:
$ DISPLAY=:1 cargo run --example basic
[works fine]
```
So perhaps this is not about `xhost`, sorry :-(

**Comment by coderedart** [comment]
i also have the same issue. i get failedtoconnect. my xhost ouput is 
`access control enabled, only authorized clients can connect`. no users or anything after that.

**Comment by notgull** [comment]
> i also have the same issue. i get failedtoconnect. my xhost ouput is
> `access control enabled, only authorized clients can connect`. no users or anything after that.
> Endeavour and KDE. xorg-server 1.20.13-2. all are updated.

Do you mind giving me the output of running `xtrace cargo run --example basic`

**Comment by coderedart** [comment]
```
➜  breadx git:(master) xtrace ~/.cargo/bin/cargo run --example basic
Function              File                                                  Line
--------------------------------------------------------------------------------
Warning: locale not supported by Xlib, locale set to C
Press return here to close xterm(/home/red/.cargo/bin/cargo).

```
it opened a new xterm terminal, and its output was 
```
warning: unused import: `env`
 --> examples/basic.rs:7:11
  |
7 | use std::{env, process};
  |           ^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: cannot specify lifetime arguments explicitly if late bound lifetime parameters are present
   --> examples/basic.rs:103:33
    |
103 |                 gc.draw_lines::<'_, _, _, &[Segment]>(
    |                                 ^^
    | 
   ::: /home/red/programming/breadx/src/display/traits/xproto/gcontext.rs:79:14
    |
79  |         dpy: &mut Dpy,
    |              - the late bound lifetime parameter is introduced here
    |
    = note: `#[warn(late_bound_lifetime_arguments)]` on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #42868 <https://github.com/rust-lang/rust/issues/42868>

  warning: 2 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/examples/basic`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FailedToConnect', examples/basic.rs:12:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by notgull** [comment]
This error comes from this file (https://github.com/bread-graphics/breadx/blob/master/src/display/connection/establish.rs#L70), where the X11 protocol specification states that, if the first byte of the setup is zero, the connection has failed.

I've created #60 in order to try to make this a bit more debuggable.

**Comment by notgull** [comment]
@coderedart Do you mind trying again on the latest version?

**Comment by coderedart** [comment]
@notgull 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FailedToConnect("Invalid MIT-MAGIC-COOKIE-1 key")', examples/basic.rs:12:58
```
from 
```
cargo run --example basic
```

**Comment by coderedart** [comment]
It finally works. i was reading up on Xauthority and apparently, some use the .Xauthority file and others use a `/var/run/sddm or whatever display manager/random key` . and the contents of my .Xauthority and that file in /var/run didn't match. once i removed the .Xauthority file and rebooted, breadx works now. although i wonder how other apps deal with this.

**Comment by notgull** [comment]
The authorization info code is an admittedly basic version of the code in LibXau (https://github.com/freedesktop/xorg-libXau). I should probably go back and make sure it runs on all machines.

**Comment by notgull** [comment]
Given that the new version relies on `x11rb-protocol` for Xauthority parsing, any future issues in that regard should be forwarded over there
