### ISSUE TITLE
GrabButton requests always fail because of the length

### ISSUE THREAD

**Issue by SorrowEater** [bread-graphics/breadx#87]
GrabButton requests fail because of the event mask field: the EventMask struct contains a u32, but the request wants a u16. One possible solution would be to make a new struct for PointerEvents, like in the X Protocol Docs (see SETofPOINTEREVENT).

**Comment by SorrowEater** [comment]
It seems that this was a 2.0.0 problem. We will begin shifting to newer versions soon, but because of how massively the structure of everything has changed, it will be difficult.

**Comment by notgull** [comment]
Sounds good, I wrote 3.0 to fix many of the issues that 2.0 had. Let me know if you have any questions.
